# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0cfa98bea33e94905996430022d3ecb698df541784dfcbd2d41cac82566dd5f48b9afab497f760ee6bd529b14847a595bfa06ceffefcc6610078bd6c017a8cc

test:
  secret_key_base: 793c42e6cb134b6b662ce6a09398b32b6fcbcdd537c1ea79f8e6af34c8ac0eb62b54bc02ba2f6ae0c45800ac8bb0fac08667a18898ab47b228aebdd109955470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
